# Generated by Django 4.1.2 on 2022-10-26 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_alter_studentaddress_student_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='dob',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='StudentAddress',
        ),
    ]
