# Generated by Django 4.1.2 on 2022-10-26 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_student_dob_delete_studentaddress'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='forename',
            field=models.CharField(default='Some string', max_length=100),
        ),
        migrations.AddField(
            model_name='student',
            name='surname',
            field=models.CharField(default='some string', max_length=100),
        ),
    ]
