# Generated by Django 4.1.2 on 2022-10-26 10:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_student_forename_student_surname'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentAddress',
            fields=[
                ('address_id', models.IntegerField(primary_key=True, serialize=False)),
                ('first_line', models.CharField(max_length=200)),
                ('post_code', models.CharField(max_length=100)),
                ('town', models.CharField(max_length=20)),
                ('Student_ID', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='catalog.student')),
            ],
        ),
    ]
