# Generated by Django 4.1.2 on 2022-10-26 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_studentaddress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='Student_ID',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='studentaddress',
            name='address_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
