# Generated by Django 4.1.2 on 2022-10-26 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_remove_studentaddress_student_id_student_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentaddress',
            name='house_number',
            field=models.IntegerField(null=True),
        ),
    ]
